# Generated by Django 5.0.9 on 2026-01-11 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('pattern', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('INCLUDE', 'Include'), ('EXCLUDE', 'Exclude')], default='INCLUDE', max_length=10)),
                ('match_field', models.CharField(choices=[('title', 'Title'), ('description', 'Description'), ('both', 'Both')], default='both', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('poll_interval_sec', models.IntegerField(default=120)),
                ('limit_items', models.IntegerField(default=10)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(unique=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('flag_y', models.BooleanField(blank=True, null=True)),
                ('flag_reason', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('SCANNED', 'Scanned'), ('CAPTIONED', 'Captioned'), ('PUBLISHED', 'Published'), ('DROPPED', 'Dropped')], default='NEW', max_length=12)),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('sentiment', models.CharField(blank=True, default='', max_length=10)),
                ('ai_model', models.CharField(blank=True, default='', max_length=50)),
                ('captioned_at', models.DateTimeField(blank=True, null=True)),
                ('ai_error', models.TextField(blank=True, default='')),
                ('wp_post_id', models.IntegerField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('wp_status', models.CharField(blank=True, default='', max_length=10)),
                ('wp_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.source')),
            ],
        ),
    ]
